### ISSUE TITLE
How to use AES crypto in Typescript

### ISSUE THREAD

**Issue by Chandrakala14** [evgenyneu/aes-crypto-web#1]
Hi,
great job!

Can you please share how to use aes-crypto for typescript in angular2.

Thanks.

**Comment by evgenyneu** [comment]
Hi @Chandrakala14, I have not used these technologies, unfortunately.  What are you hoping to achieve in your app, from the user's perspective?

**Comment by Chandrakala14** [comment]
aes encryption and decryption in web, but I want to use same javascript code in typescript.

**Comment by evgenyneu** [comment]
Oh, I see, then you can probably use CryptoJS library https://code.google.com/archive/p/crypto-js/. It's pure JavaScript, so it can be used in any framework.

This repository is for the aescrypto.com web site, and it also uses CryptoJS.
